### ISSUE TITLE
Should the pods/containers be restarted after a reboot?

### ISSUE THREAD

**Issue by kastl-ars** [Tronde/ansible_role_deploy_nextcloud_with_mariadb_pod#2]
Hi Jörg,

I might be missing an option or setting, but in my testing the pods are no longer running after the hosts reboots. Is this intentional or am I doing something wrong?

Kind Regards
Johannes

**Comment by Tronde** [comment]
Hi Johannes,  
That's by design. You're not doing something wrong.

Back when I created this role I preferred services to stay down when the host reboots unexpectedly. When updating the host I use playbooks to patch, reboot, and start services. In case of an unexpected reboot I want the services to stay down to be able to troubleshoot the cause before everything is trying to start again.

I like to keep it this way for a while. When refactoring the role I would like to use Quadlets. Unfortunately the podman version in Debian 12 (Bookworm) doesn't know about them.

Does this answer your question?  
Do you have suggestions on how to improve it?

Best regards,  
Jörg

**Comment by kastl-ars** [comment]
Thanks for the fast reply, Jörg! Then I know I am not doing something wrong.

During refactoring, you could think about adding an option to allow the user to decide, if the service should be enabled to start after a reboot.
